Wip 7 , 5 and 6
csci320/weintraubm320 pull request #9
Opened 2020-09-09 15:34 UTC by Weintraubm

2020-09-10 02:03 UTC, smattingly requested changes
Most of the review comments are just for feedback. The only thing I'd like you to change is 7-5. Because this PR is proper subsets of multiple exercise sets, I'm unclear what if anything should be checked off in Sakai, but I'll figure that out.

2020-09-10 02:03 UTC, smattingly commented on exercise7-5.txt
> +because it only has one primary key
Every table has one primary key, by definition. I think you've got the idea, but haven't expressed in correctly.

2020-09-11 18:03 UTC, smattingly approved these changes
👍

2020-09-11 18:03 UTC, smattingly commented on exercise7-5.txt
> +because it has no trivial keys and only needs one reference to connect to other tables rather than multiple references
Again, I think you have the idea. With proper terminology: the primary key is a single field (not a compound key), therefore no proper subsets of the key, therefore no partial dependencies can exist.

2020-09-13 17:33 UTC, Weintraubm reviewed
@smattingly

2020-09-14 00:56 UTC, smattingly approved these changes
8-1 looks good. Would you please merge (and thus close) this PR? Then I can just track new work by watching commits. It has become difficult to keep track of things when mixed together this way-- I should have planned better.

2020-09-14 14:06 UTC, merged